apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quantaid.fullname" . }}-config
  labels:
    {{- include "quantaid.labels" . | nindent 4 }}
data:
  db_host: {{ .Release.Name }}-postgresql
