apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quantaid.fullname" . }}
  labels:
    {{- include "quantaid.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "quantaid.fullname" . }}
                port:
                  name: http
