apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quantaid.fullname" . }}-secret
  labels:
    {{- include "quantaid.labels" . | nindent 4 }}
type: Opaque
data:
  db_password: {{ .Values.postgresql.auth.password | b64enc | quote }}
